# wrangler.toml
name = "bila-rosa" # Ensure this matches the name in your Cloudflare dashboard
main = "src/main.jsx"            # This is your Worker's entry point (even if it's minimal)
compatibility_date = "2025-06-13" # Or whatever today's date is, or a very recent date

# THIS IS THE CRUCIAL CHANGE for Workers with static assets
[assets]
directory = "./dist" # Point this to your Vite build output directory
