# wrangler.toml
name = "bila-rosa" # This will be the name of your Cloudflare Pages project
#main = "src/index.ts" # Placeholder, not strictly used for static Pages deployments
compatibility_date = "2024-01-01" # Set to a recent date, e.g., "2024-06-13" or today's date
                               # This ensures your Worker/Pages environment uses recent features.

# This section tells Cloudflare Pages where your built output will be
[pages]
build_output_dir = "./dist"
